# アプリ固有の設定ファイル
mail:
  account: "********@gmail.com"
  app_pwd: "********"
  to_addr: "********@gmail.com"

weather:
  city_id: "140010"

news:
  apikey: "********"

tts:
  type: 0                             # 0:VOICEVOX  1:ElevenLabs  2:OpenAI TTS
  model: ""                           # VOICEVOX (modelは未対応)
  #model: "eleven_multilingual_v2"    # ElevenLabs
  #model: "tts-1"                     # OpenAI TTS
  voice: "3"                          # VOICEVOX (ずんだもん)
  #voice: "AZnzlk1XvdvUeBnXmlld"      # ElevenLabs
  #voice: "alloy"                     # OpenAI TTS